version = 1
SPDX-PackageName = "cati"
SPDX-PackageSupplier = "Uwe Jugel <ubunatic@noreply.codeberg.org>"
SPDX-PackageDownloadLocation = "https://codeberg.org/ubunatic/cati"

[[annotations]]
path = ["**"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 Uwe Jugel"
SPDX-License-Identifier = "AGPL-3.0-or-later"

[[annotations]]
path = ["assets/book/mermaid.min.js"]
precedence = "override"
SPDX-FileCopyrightText = "2026 Mermaid Contributors"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = ["assets/book/mermaid-init.js"]
precedence = "override"
SPDX-FileCopyrightText = "2026 mdBook Contributors"
SPDX-License-Identifier = "MPL-2.0"

